### PR TITLE
Include w3c/web-platform-tests as submodule and use its version of testharness.js

### PR DESCRIPTION
**Pull request by alancutter**
This change pulls in https://github.com/w3c/web-platform-tests as a submodule in test/web-platform-tests and redirects existing uses of testharness.js to the version used by that.

This change is in preparation for automated testing of web-platform-tests/web-animations with the polyfill.

### CODE REVIEW

**Comment by suzyh** [comment]
More or less LGTM. My main concern is that it's not 100% clear what part of the change comes from importing recent changes to the testharness and what part is added by you for the polyfill logic. I'm not sure what to suggest beyond splitting the second commit into two - the import and your extra logic.

How often does the testharness update? Are we going to need to pull in more changes like this in future?

**Comment by alancutter** [comment]
We'll need to update this as often as web-platform-tests requires a new version.
I can imagine that's a bit of manual work that would be nice to avoid, I can probably use the inner submodule checkout in web-platform-tests instead and just proxy the testharnessreport.js file in Karma. Does that sound like a better option?

**Comment by suzyh** [comment]
Yeah, that sounds preferable. Thanks!

**Comment by suzyh** [comment]
LGTM

**Pull request merged**
