### PR TITLE
Remove old naming

### PR DESCRIPTION
**Pull request by rjwright**

### CODE REVIEW

**Comment by rjwright** [comment]
@shans @dstockwell I think this is it. Now we can expose the animation constructor, but I will do that in a different patch.

**Comment by dstockwell** [comment]
lgtm

**Comment by shans** [comment]
Would you mind checking if our demos are borken now too? Doug points out they'll already be busted because the deprecation warning turns into an error 90 days out.

**Comment by alancutter** [comment]
FYI some of the Web Animation demos are broken on Chrome Canary at the moment, it's best to test on beta or earlier until the fix lands (https://codereview.chromium.org/1196163003).

**Pull request merged**
