### PR TITLE
Catch up when gCS is called after long idle period

### PR DESCRIPTION
**Pull request by shans**
One thing I don't like  about this: performance.now() doesn't seem aligned that well with rAF. So this probably makes one of the frame intervals < 16ms. Probably not noticeable though.

### CODE REVIEW

**Comment by shans** [comment]
@dstockwell

**Comment by shans** [comment]
(addresses #321)

**Comment by dstockwell** [comment]
lgtm

**Comment by rjwright** [comment]
Is there a reason this hasn't been merged?

**Comment by shans** [comment]
Don't know why not. Probably worth poking Travis again before attempting to though.

**Comment by shans** [comment]
Travis still happy. Might merge it now.

**Pull request merged**
