### PR TITLE
Not automatically play created animation

### LINKED ISSUE #388: Animations created with the Animation constructor start playing automatically

### PR DESCRIPTION
**Pull request by hgl**
Fixes #388

### CODE REVIEW

**Comment by hgl** [comment]
Oops, it's based on my previous PR. Let me know if I should rebase.

**Comment by hgl** [comment]
Should https://github.com/hgl/web-animations-next/blob/612fe61b919e7ea6f7a463d6b66ab19b1996bdf4/src/web-animations-next-animation.js#L80
 be changed to `this._cancel()` also?

**Comment by hgl** [comment]
This PR is crap. I forgot canceling an animation actually wipes out its current time.

But somehow it works with the native implementation, which is why I was fooled into thinking I got a working solution: http://jsbin.com/fovexulehi/1/edit?html,js,output

I will give it another try (maybe pause child animations after their current times have been set?).

**Comment by alancutter** [comment]
web-animations-next is deprecated, all development has moved to web-animations-js dev branch.

Sounds like this change isn't suitable, closing. Will continue to resolve this bug in https://github.com/web-animations/web-animations-next/issues/388.

**Pull request closed without merging**
